# tasks file
---
- name: get download name
  ansible.builtin.shell: >
    echo docker-compose-$(uname -s)-$(uname -m)
  register: _get_download_name
  changed_when: false
  tags:
    - docker-compose-install-download
    - docker-compose-install-download-name

- name: create (download) directory
  ansible.builtin.file:
    path: "{{ docker_compose_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - docker-compose-install-download
    - docker-compose-install-download-directory

- name: download
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/{{ _get_download_name.stdout }}"
    dest: "{{ docker_compose_downloads_path }}/{{ _get_download_name.stdout }}-{{ docker_compose_version }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - docker-compose-install-download
    - docker-compose-install-download-get

- name: install
  ansible.builtin.file:
    src: "{{ docker_compose_downloads_path }}/{{ _get_download_name.stdout }}-{{ docker_compose_version }}"
    dest: "{{ docker_compose_install_prefix }}/docker-compose"
    state: link
    force: true
  tags:
    - docker-compose-install-install
    - docker-compose-install-install-symlink

- name: verify
  ansible.builtin.command: >
    {{ docker_compose_install_prefix }}/docker-compose --version
  register: _verify_version
  failed_when: "docker_compose_version not in _verify_version.stdout"
  changed_when: false
  tags:
    - docker-compose-install-verify
