# tasks file for docker-compose
---
- name: get download name
  shell: echo docker-compose-$(uname -s)-$(uname -m)
  register: get_download_name
  changed_when: false
  tags:
    - docker-compose-install-download
    - docker-compose-install-download-name

- name: create (download) directory
  file:
    path: "{{ docker_compose_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - docker-compose-install-download
    - docker-compose-install-download-directory

- name: download
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/{{ get_download_name.stdout }}"
    dest: "{{ docker_compose_downloads_path }}/{{ get_download_name.stdout }}-{{ docker_compose_version }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - docker-compose-install-download
    - docker-compose-install-download-get

- name: install
  file:
    src: "{{ docker_compose_downloads_path }}/{{ get_download_name.stdout }}-{{ docker_compose_version }}"
    dest: "{{ docker_compose_install_prefix }}/docker-compose"
    state: link
    force: true
  tags:
    - docker-compose-install-install
    - docker-compose-install-install-symlink
